lidar:
  dst_port: 2368
  src_port: 2369
  dst_ip: 10.72.32.61

mysql:
  user: df_dk_admin
  pwd: Hx2024
  ip: 10.72.32.61
  port: 3306
  db: df_dk_admin

mqtt:
  ip: 10.205.51.243
  port: 1883
  user: admin_df
  pwd: Huazhi@2025
  topic: DF/6FS

savecloud: 0

rectangle:
  min_h: -60
  max_h: 60
  min_v: -13
  max_v: 13

pcl:
  # 对于静止或缓慢移动的物体，可以设置较小的值，如0.05-0.1m。
  # 对于快速移动的物体，可能需要设置更大的值，如0.5-1m。
  # 通常从一个较大的值开始，然后逐步减小直到获得最佳结果。
  max_correspondence_distance: 0.5
  # 通常设置在 30 到 100 之间
  # 对于实时应用，可能需要设置较小的值，如 30-50
  # 对于离线处理且需要高精度的场景，可以设置更大的值，如 100-200
  max_iterations: 50
  # 通常设置在 0.001 到 0.1 之间
  # 对于需要高精度的应用，可以设置较小的值，如 0.001 或 0.005
  # 对于实时应用或对精度要求不是特别高的场景，可以设置较大的值，如 0.05 或 0.1
  euclidean_fitness_epsilon: 0.005
