# 船舶点云 NDT 粗配准参数
ndt:
  voxel:
    x: 0.1
    y: 0.1
    z: 0.1
  max_iter: 30
  trans_eps: 1e-6
  step_size: 0.1
  resolution: 0.5
  fit_thresh: 1.5

# 船舶点云 GICP 精配准参数
gicp:
  voxel:
    x: 0.05
    y: 0.05
    z: 0.05
  use_reciprocal: true
  max_corr_dist: 0.3
  max_iter: 150
  trans_eps: 1e-6
  euclid_eps: 1e-6
  rot_eps: 1e-3
  rand_num: 15
  fit_thresh: 1.0
  score_radius: 0.5